# Generated by Django 5.2.17 on 2026-09-19 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placement', '0001_initial'),
        ('postings', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='postings', to='students.department'),
        ),
        migrations.AddField(
            model_name='posting',
            name='drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postings', to='placement.placementdrive'),
        ),
        migrations.AddField(
            model_name='posting',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='postings', to='postings.skill'),
        ),
        migrations.AddIndex(
            model_name='posting',
            index=models.Index(fields=['deadline'], name='postings_po_deadlin_6cdfd7_idx'),
        ),
        migrations.AddIndex(
            model_name='posting',
            index=models.Index(fields=['type'], name='postings_po_type_679e11_idx'),
        ),
        migrations.AddIndex(
            model_name='posting',
            index=models.Index(fields=['company'], name='postings_po_company_0a83e0_idx'),
        ),
        migrations.AddIndex(
            model_name='posting',
            index=models.Index(fields=['status'], name='postings_po_status_24c835_idx'),
        ),
    ]
