# Generated by Django 5.2.17 on 2026-09-19 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='postings.posting'),
        ),
    ]
