# Generated by Django 5.2.17 on 2026-09-19 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['posting'], name='application_posting_28842f_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['student'], name='application_student_979a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_1508e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('posting', 'student'), name='unique_student_posting_application'),
        ),
    ]
